name: PluginCore
version: ${project.version}
main: me.domirusz24.plugincore.FakePluginClass
api-version: 1.13
depend: [ProtocolLib, WorldEdit, PlaceholderAPI]
softdepend: [Multiverse-Core]
authors: [DomiRusz24]
description: PluginCore for my other plugins




